[package]
name = "script"
version = "0.1.0"
authors = ["Ziyuan Liu <ziyuan.liu@gmail.com>"]

[dependencies]
bitcrypto = { path = "../crypto" }
chain = { path = "../chain" }
keys = { path = "../keys" }
primitives = { path = "../primitives" }
serialization = { path = "../serialization" }
log = "0.4"
